<a href="https://colab.research.google.com/github/AHS2020/Python_UERJ/blob/master/ArthurHenrique_e_LuizFernando_Projeto_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PROJETO

Questão 1 - Criar uma `Classe` Perceptron em Python. Vocês podem seguir o esqueleto de Classe apresentado abaixo.




In [1]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

class MyPerceptron():

    def __init__(self, no_of_inputs, threshold=100, learning_rate=0.01):
        '''
        método de inicialização que tem os seguintes atributos:
        no_of_inputs: número de features passadas como input ao perceptron
        threshold: número de iterações de atualização do peso
        learning_rate: taxa com a qual os pesos são atualizados a cada iteração
        weights: inicialização dos pesos (dica: pode inicializar com método np.zeros). Não se esquecer que o vetor dos pesos
        terá no_of_inputs + 1 elementos por conta do bias que é o primeiro elemento.
        '''
        self.b = 0
        self.weights = np.zeros(no_of_inputs)              
        self.threshold = threshold
        self.learning_rate = learning_rate
           
    def predict(self, inputs):
      '''
      método de implementação da função de ativação.
      inputs: array com o conjunto de inputs (features). No projeto pedimos que considerassem o comprimento e largura da pétala da Iris.
      Não se esquecer que o produto da função de ativação é um produto escalar e pode ser calculado pelo método np.dot
      '''         
      f = np.heaviside(np.dot(self.weights, inputs) + self.b, 0)
      return f

    def train(self, training_inputs, labels):
      '''
      método de treino. É aqui que os pesos são atualizados um certo número de vezes (determinado pelo valor do threshold).
      Nesse método é feita a comparação entre o resultado da função de ativação (predição) e
      o resultado esperado (label).
      O método deve atualizar tanto os pesos quanto o bias (lembre que o bias é o primeiro valor do vetor peso e tem input 1.)
      A atualização é feita iterativamente um número (threshold) de vezes.
      '''
      for i in range(self.threshold):
          for j in range(len(training_inputs)):
            prediction = self.predict(training_inputs[j])
            error = labels[j] - prediction
            self.weights += self.learning_rate * error * training_inputs[j]
            self.b += self.learning_rate * error * 1

In [2]:
print(iris.target_names)    # target = label
print(iris.feature_names)   # features = características
# Pelo primeiro print acima, as features são: 0: sepal length, 1: sepal width, 2: petal length, 3: petal width

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


> Pelo primeiro print acima diz que os targets são: 0: Setosa, 1: Versicolor e 2: Virginica.

> Já o segundo print diz que as features são: 0: sepal length, 1: sepal width, 2: petal length, 3: petal width.





Questão 2 - Aplique essa classe nos dados das flores Iris para determinar se uma Íris com um certo comprimento e largura de **pétala** e **sépala**  é uma Íris Setosa.



In [5]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

Percep = MyPerceptron(4)

X = iris.data[:, (0,1,2,3)]               # inputs
y = (iris.target == 0).astype(int)        # label = iris setosa. Retorna uma lista com os labels da Iris-Setosa. 0: não, 1: sim   

# Separação da amostra das Iris em duas: uma para treino e outra para teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)

#print(X_train)
#print(" ")
#print(X_test)
#print(" ")
#print(y_train)
#print(" ")
#print(y_test)

In [6]:
Treino = Percep.train(X_train,y_train)
Predição = []

for i in range(len(X_test)):
  Pred = Percep.predict(X_test[i])
  Predição.append(int(Pred))

a = Predição
b = ''.join(str(a).split(','))

print(b)
print(" ")
print(y_test)

[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]
 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0
 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0
 0]


> Utilizando o MyPerceptron, o resultado obtido foi que a lista de predição tem os mesmos dados da lista de teste (y_test).


Questão 3 - Compare o resultado da sua classe com a classe Peceptron do módulo do scikit-learn `linear_model`.



In [7]:
#A partir do módulo do scikit-learn linear_model.
Percep_sl = Perceptron()                  
Treino_2 = Percep_sl.fit(X_train,y_train)
Predição_2 = []

for i in range(len(X_test)):
  Pred = Percep_sl.predict([X_test[i]])
  Predição_2.append(int(Pred))

a_2 = Predição_2
b_2 = ''.join(str(a_2).split(','))

print(b_2)
print(" ")
print(y_test)

[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]
 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0
 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0
 0]


> Utilizando o Peceptron do módulo do scikit-learn `linear_model`, o resultado obtido foi que a lista de predição tem os mesmos dados da lista de teste (y_test).

In [8]:
print(b)
print(" ")
print(b_2)

[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]
 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]


> Os resultados obtidos com MyPerceptron e os obtidos com Peceptron do módulo do scikit-learn `linear_model` são exatamente os mesmos resultados para esses dados.

Questão 4 - Você pode pensar em algum outro exemplo em que possa aplicar o modelo do Perceptron? Quando esse modelo falha?

> Podemos aplicar o modelo do Perceptron para todo sistema binário, ou seja com duas opções de resposta.

> Esse método pode falhar quando se testa os limites de seu aprendizado. Se chegarmos com dados além dos limites que ela aprendeu é possível achar uma falha por exemplo:

> Encontrando os limites dos dados do nosso experimento.




In [9]:
for i in range(150): #Setosa
  if i < 50:
    print(X[i])

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]
[5.4 3.9 1.7 0.4]
[4.6 3.4 1.4 0.3]
[5.  3.4 1.5 0.2]
[4.4 2.9 1.4 0.2]
[4.9 3.1 1.5 0.1]
[5.4 3.7 1.5 0.2]
[4.8 3.4 1.6 0.2]
[4.8 3.  1.4 0.1]
[4.3 3.  1.1 0.1]
[5.8 4.  1.2 0.2]
[5.7 4.4 1.5 0.4]
[5.4 3.9 1.3 0.4]
[5.1 3.5 1.4 0.3]
[5.7 3.8 1.7 0.3]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.7 0.2]
[5.1 3.7 1.5 0.4]
[4.6 3.6 1.  0.2]
[5.1 3.3 1.7 0.5]
[4.8 3.4 1.9 0.2]
[5.  3.  1.6 0.2]
[5.  3.4 1.6 0.4]
[5.2 3.5 1.5 0.2]
[5.2 3.4 1.4 0.2]
[4.7 3.2 1.6 0.2]
[4.8 3.1 1.6 0.2]
[5.4 3.4 1.5 0.4]
[5.2 4.1 1.5 0.1]
[5.5 4.2 1.4 0.2]
[4.9 3.1 1.5 0.2]
[5.  3.2 1.2 0.2]
[5.5 3.5 1.3 0.2]
[4.9 3.6 1.4 0.1]
[4.4 3.  1.3 0.2]
[5.1 3.4 1.5 0.2]
[5.  3.5 1.3 0.3]
[4.5 2.3 1.3 0.3]
[4.4 3.2 1.3 0.2]
[5.  3.5 1.6 0.6]
[5.1 3.8 1.9 0.4]
[4.8 3.  1.4 0.3]
[5.1 3.8 1.6 0.2]
[4.6 3.2 1.4 0.2]
[5.3 3.7 1.5 0.2]
[5.  3.3 1.4 0.2]


#Setosa
> Mínimos de 1.0 e 0.1 para petal length e petal width respectivamente.

> Máximos de 1.9 e 0.6 para petal length e petal width respectivamente.

> Mínimos de 4.3 e 2.3 para sepal length e sepal width respectivamente.

> Máximos de 5.8 e 4.4 para sepal length e sepal width respectivamente.

In [10]:
for i in range(150): #Versicolor
  if i > 49 and i < 100:
    print(X[i])

[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4.5 1.3]
[6.3 3.3 4.7 1.6]
[4.9 2.4 3.3 1. ]
[6.6 2.9 4.6 1.3]
[5.2 2.7 3.9 1.4]
[5.  2.  3.5 1. ]
[5.9 3.  4.2 1.5]
[6.  2.2 4.  1. ]
[6.1 2.9 4.7 1.4]
[5.6 2.9 3.6 1.3]
[6.7 3.1 4.4 1.4]
[5.6 3.  4.5 1.5]
[5.8 2.7 4.1 1. ]
[6.2 2.2 4.5 1.5]
[5.6 2.5 3.9 1.1]
[5.9 3.2 4.8 1.8]
[6.1 2.8 4.  1.3]
[6.3 2.5 4.9 1.5]
[6.1 2.8 4.7 1.2]
[6.4 2.9 4.3 1.3]
[6.6 3.  4.4 1.4]
[6.8 2.8 4.8 1.4]
[6.7 3.  5.  1.7]
[6.  2.9 4.5 1.5]
[5.7 2.6 3.5 1. ]
[5.5 2.4 3.8 1.1]
[5.5 2.4 3.7 1. ]
[5.8 2.7 3.9 1.2]
[6.  2.7 5.1 1.6]
[5.4 3.  4.5 1.5]
[6.  3.4 4.5 1.6]
[6.7 3.1 4.7 1.5]
[6.3 2.3 4.4 1.3]
[5.6 3.  4.1 1.3]
[5.5 2.5 4.  1.3]
[5.5 2.6 4.4 1.2]
[6.1 3.  4.6 1.4]
[5.8 2.6 4.  1.2]
[5.  2.3 3.3 1. ]
[5.6 2.7 4.2 1.3]
[5.7 3.  4.2 1.2]
[5.7 2.9 4.2 1.3]
[6.2 2.9 4.3 1.3]
[5.1 2.5 3.  1.1]
[5.7 2.8 4.1 1.3]


#Versicolor

> Mínimos de 3.0 e 1.0 para petal length e petal width respectivamente.

> Máximos de 5.1 e 1.8 para petal length e petal width respectivamente.

> Mínimos de 4.9 e 2.0 para sepal length e sepal width respectivamente.

> Máximos de 7.0 e 3.4 para sepal length e sepal width respectivamente.

In [11]:
for i in range(150): #Virginica
  if i > 99:
    print(X[i])

[6.3 3.3 6.  2.5]
[5.8 2.7 5.1 1.9]
[7.1 3.  5.9 2.1]
[6.3 2.9 5.6 1.8]
[6.5 3.  5.8 2.2]
[7.6 3.  6.6 2.1]
[4.9 2.5 4.5 1.7]
[7.3 2.9 6.3 1.8]
[6.7 2.5 5.8 1.8]
[7.2 3.6 6.1 2.5]
[6.5 3.2 5.1 2. ]
[6.4 2.7 5.3 1.9]
[6.8 3.  5.5 2.1]
[5.7 2.5 5.  2. ]
[5.8 2.8 5.1 2.4]
[6.4 3.2 5.3 2.3]
[6.5 3.  5.5 1.8]
[7.7 3.8 6.7 2.2]
[7.7 2.6 6.9 2.3]
[6.  2.2 5.  1.5]
[6.9 3.2 5.7 2.3]
[5.6 2.8 4.9 2. ]
[7.7 2.8 6.7 2. ]
[6.3 2.7 4.9 1.8]
[6.7 3.3 5.7 2.1]
[7.2 3.2 6.  1.8]
[6.2 2.8 4.8 1.8]
[6.1 3.  4.9 1.8]
[6.4 2.8 5.6 2.1]
[7.2 3.  5.8 1.6]
[7.4 2.8 6.1 1.9]
[7.9 3.8 6.4 2. ]
[6.4 2.8 5.6 2.2]
[6.3 2.8 5.1 1.5]
[6.1 2.6 5.6 1.4]
[7.7 3.  6.1 2.3]
[6.3 3.4 5.6 2.4]
[6.4 3.1 5.5 1.8]
[6.  3.  4.8 1.8]
[6.9 3.1 5.4 2.1]
[6.7 3.1 5.6 2.4]
[6.9 3.1 5.1 2.3]
[5.8 2.7 5.1 1.9]
[6.8 3.2 5.9 2.3]
[6.7 3.3 5.7 2.5]
[6.7 3.  5.2 2.3]
[6.3 2.5 5.  1.9]
[6.5 3.  5.2 2. ]
[6.2 3.4 5.4 2.3]
[5.9 3.  5.1 1.8]


#Virginica

> Mínimos de 4.5 e 1.4 para petal length e petal width respectivamente.

> Máximos de 6.9 e 2.5 para petal length e petal width respectivamente.

> Mínimos de 4.9 e 2.2 para sepal length e sepal width respectivamente.

> Máximos de 7.9 e 3.8 para sepal length e sepal width respectivamente.

> No experimento buscamos a Íris Setosa, então trabalharemos em torno de seus limites.

> Observando os dados é possível perceber que as larguras e os compimentos de sepalas dos três tipos de Íris se misturam, logo serão utilizados os máximos desses valores para a Íris Setosa, assim só levaremos em conta os dados das pétalas.

> Já as larguras e comprimentos de pétalas da Íris setosa se distaca dos outros tipos de Íris. Então para buscar falhas, precisamos trabalhar nos limites dos dados de largura e comprimento para as pétalas de Íris Setosa.




In [84]:
Pred_0 = Percep.predict([5.8,4.4,1.0,0.1])
print(Pred_0)
Pred_1 = Percep.predict([5.8,4.4,0,0])
print(Pred_1)
Pred_2 = Percep.predict([1000,1000,0,0])
print(Pred_2)
Pred_3 = Percep.predict([1000,1000,1.0,0.1])
print(Pred_3)
Pred_4 = Percep.predict([0,0,0,0])
print(Pred_4)

1.0
1.0
1.0
1.0
1.0


> Testando o mínimo dos dados de Setosa, pode-se ver que o peceptron reconhece que, Íris com qualquer tamanho de sepala ou até sem sepalas e pétalas pequenas de mais ou até sem pétalas são todas Íris Setosas.


#Setosa

> Máximos de 1.9 e 0.6 para petal length e petal width respectivamente.

#Versicolor

> Mínimos de 3.0 e 1.0 para petal length e petal width respectivamente.

In [74]:
Pred_01 = Percep.predict([5.8,4.4,1.9,0.6])
print(Pred_01)
Pred_02 = Percep.predict([5.8,4.4,2.0,0.7])
print(Pred_02)

print(' ')

Pred_03 = Percep.predict([5.8,4.4,3.0,1.0])
print(Pred_03)
Pred_04 = Percep.predict([5.8,4.4,3.0,0.6])
print(Pred_02)
Pred_05 = Percep.predict([5.8,4.4,3.1,0.6])
print(Pred_05)
Pred_06 = Percep.predict([5.8,4.4,3.0,0.7])
print(Pred_06)

print(' ')

Pred_07 = Percep.predict([5.8,4.4,3.0,1.0])
print(Pred_07)
Pred_08 = Percep.predict([5.8,4.4,1.9,1.0])
print(Pred_08)
Pred_09 = Percep.predict([5.8,4.4,1.9,3.0])
print(Pred_09)
Pred_10 = Percep.predict([5.8,4.4,2.0,3.0])
print(Pred_10)
Pred_11 = Percep.predict([5.8,4.4,2.0,1.0])
print(Pred_11)
Pred_11 = Percep.predict([5.8,4.4,2.8,1.0])
print(Pred_11)
Pred_11 = Percep.predict([5.8,4.4,2.8,1.1])
print(Pred_11)
Pred_11 = Percep.predict([5.8,4.4,2.8,1.2])
print(Pred_11)

1.0
1.0
 
0.0
1.0
0.0
0.0
 
0.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0


> Testando os limites entre os máximos dos dados das pétalas de Íris Setosa e os mínimo dos dados das pétalas de Íris Versicolor, pode-se ver que o peceptron reconhece que pétalas muito grandes para serem Setosas ou seja muito perto dos limites das petalas de íris Versicolos também são consideradas Setosas.

In [147]:
Pred_12 = Percep.predict([1000,1000,1.9,0.6])
print(Pred_12)
Pred_13 = Percep.predict([1000,1000,2.0,0.7])
print(Pred_13)

print(' ')

Pred_14 = Percep.predict([1000,1000,3.0,1.0])
print(Pred_14)
Pred_15 = Percep.predict([1000,1000,3.0,0.6])
print(Pred_15)
Pred_16 = Percep.predict([1000,1000,3.1,0.6])
print(Pred_16)
Pred_17 = Percep.predict([1000,1000,3.0,0.7])
print(Pred_17)

print(' ')

Pred_18 = Percep.predict([1000,1000,3.0,1.0])
print(Pred_18)
Pred_19 = Percep.predict([1000,1000,1.9,1.0])
print(Pred_19)
Pred_20 = Percep.predict([1000,1000,1.9,3.0])
print(Pred_20)
Pred_21 = Percep.predict([1000,1000,2.0,3.0])
print(Pred_21)
Pred_22 = Percep.predict([1000,1000,2.0,1.0])
print(Pred_22)
Pred_23 = Percep.predict([1000,1000,2.8,1.0])
print(Pred_23)
Pred_24 = Percep.predict([1000,1000,2.8,1.1])
print(Pred_24)
Pred_25 = Percep.predict([1000,1000,2.8,1.2])
print(Pred_25)

print(' ')

Pred_26 = Percep.predict([2000,2000,1000,500])
print(Pred_26)
Pred_27 = Percep.predict([0,4000,2000,1000])
print(Pred_27)

1.0
1.0
 
1.0
1.0
1.0
1.0
 
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
 
1.0
1.0


> Além disso, quando se extrapola os dados de sepalas os limites para se considerar uma Íris como Setosa ficam muito grandes, como se pode ver em Pred_26. Mas como vemos em Pred_27 só é necessário extrapolar os dados de comprimento de sepalas.