<a href="https://colab.research.google.com/github/AHS2020/Python_UERJ/blob/master/ArthurHenrique_e_LuizFernando_Projeto_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PROJETO

1. Criar uma `Classe` Perceptron em Python. Vocês podem seguir o esqueleto de Classe apresentado abaixo.




In [ ]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

class MyPerceptron():

    def __init__(self, no_of_inputs, threshold=100, learning_rate=0.01):
        '''
        método de inicialização que tem os seguintes atributos:
        no_of_inputs: número de features passadas como input ao perceptron
        threshold: número de iterações de atualização do peso
        learning_rate: taxa com a qual os pesos são atualizados a cada iteração
        weights: inicialização dos pesos (dica: pode inicializar com método np.zeros). Não se esquecer que o vetor dos pesos
        terá no_of_inputs + 1 elementos por conta do bias que é o primeiro elemento.
        '''
        self.b = 0
        self.weights = np.zeros(no_of_inputs)              
        self.threshold = threshold
        self.learning_rate = learning_rate
           
    def predict(self, inputs):
      '''
      método de implementação da função de ativação.
      inputs: array com o conjunto de inputs (features). No projeto pedimos que considerassem o comprimento e largura da pétala da Iris.
      Não se esquecer que o produto da função de ativação é um produto escalar e pode ser calculado pelo método np.dot
      '''         
      f = np.heaviside(np.dot(self.weights, inputs) + self.b, 0)
      return f

    def train(self, training_inputs, labels):
      '''
      método de treino. É aqui que os pesos são atualizados um certo número de vezes (determinado pelo valor do threshold).
      Nesse método é feita a comparação entre o resultado da função de ativação (predição) e
      o resultado esperado (label).
      O método deve atualizar tanto os pesos quanto o bias (lembre que o bias é o primeiro valor do vetor peso e tem input 1.)
      A atualização é feita iterativamente um número (threshold) de vezes.
      '''
      for i in range(self.threshold):
          for j in range(len(training_inputs)):
            prediction = self.predict(training_inputs[j])
            error = labels[j] - prediction
            self.weights += self.learning_rate * error * training_inputs[j]
            self.b += self.learning_rate * error * 1

In [ ]:
print(iris.target_names)    # target = label
print(iris.feature_names)   # features = características
# Pelo primeiro print acima, as features são: 0: sepal length, 1: sepal width, 2: petal length, 3: petal width

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


> Pelo primeiro print acima diz que os targets são: 0: Setosa, 1: Versicolor e 2: Virginica.

> Já o segundo print diz que as features são: 0: sepal length, 1: sepal width, 2: petal length, 3: petal width.





2. Aplique essa classe nos dados das flores Iris para determinar se uma Iris com um certo comprimento e largura da **pétala** é uma Iris Setosa.



In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

Percep = MyPerceptron(2)

# Vamos selecionar somente as features petal length e petal width:
X = iris.data[:, (2,3)]               # inputs
y = (iris.target == 0).astype(int)    # label = iris setosa. Retorna uma lista com os labels da Iris-Setosa. 0: não, 1: sim   

# Separação da amostra das Iris em duas: uma para treino e outra para teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50, random_state=42)

#print(X_train)
#print(" ")
#print(X_test)
#print(" ")
#print(y_train)
#print(" ")
#print(y_test)

In [ ]:
Treino = Percep.train(X_train,y_train)
Predição = []

for i in range(len(X_test)):
  Pred = Percep.predict(X_test[i])
  Predição.append(int(Pred))

a = Predição
b = ''.join(str(a).split(','))

print(b)
print(" ")
print(y_test)

[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]
 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0
 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0
 0]


> Utilizando o MyPerceptron, o resultado obtido foi que a lista de predição tem os mesmos dados da lista de teste (y_test).


3. Compare o resultado da sua classe com a classe Peceptron do módulo do scikit-learn `linear_model`.



In [ ]:
#A partir do módulo do scikit-learn linear_model.
Percep_sl = Perceptron()                  # dois inputs: comprimento e largura da pétala
Treino_2 = Percep_sl.fit(X_train,y_train) # Train
Predição_2 = []

for i in range(len(X_test)):
  Pred = Percep_sl.predict([X_test[i]])
  Predição_2.append(int(Pred))

a_2 = Predição_2
b_2 = ''.join(str(a_2).split(','))

print(b_2)
print(" ")
print(y_test)

[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]
 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0
 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0
 0]


> Utilizando o Peceptron do módulo do scikit-learn `linear_model`, o resultado obtido foi que a lista de predição tem os mesmos dados da lista de teste (y_test).

In [ ]:
print(b)
print(" ")
print(b_2)

[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]
 
[0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0]


> Os resultados obtidos com MyPerceptron e os obtidos com Peceptron do módulo do scikit-learn `linear_model` são exatamente os mesmos resultados para esses dados.

4. Você pode pensar em algum outro exemplo em que possa aplicar o modelo do Perceptron? Quando esse modelo falha?

> Podemos aplicar o modelo do Perceptron para todo sistema binário, ou seja com duas opções de resposta.

> Esse método pode falhar quando se testa os limites de seu aprendizado. Se chegarmos com dados além dos limites que ela aprendeu é possível achar uma falha por exemplo:

In [ ]:
for i in range(150): #Setosa
  if i < 50:
    print(X[i])

[1.4 0.2]
[1.4 0.2]
[1.3 0.2]
[1.5 0.2]
[1.4 0.2]
[1.7 0.4]
[1.4 0.3]
[1.5 0.2]
[1.4 0.2]
[1.5 0.1]
[1.5 0.2]
[1.6 0.2]
[1.4 0.1]
[1.1 0.1]
[1.2 0.2]
[1.5 0.4]
[1.3 0.4]
[1.4 0.3]
[1.7 0.3]
[1.5 0.3]
[1.7 0.2]
[1.5 0.4]
[1.  0.2]
[1.7 0.5]
[1.9 0.2]
[1.6 0.2]
[1.6 0.4]
[1.5 0.2]
[1.4 0.2]
[1.6 0.2]
[1.6 0.2]
[1.5 0.4]
[1.5 0.1]
[1.4 0.2]
[1.5 0.2]
[1.2 0.2]
[1.3 0.2]
[1.4 0.1]
[1.3 0.2]
[1.5 0.2]
[1.3 0.3]
[1.3 0.3]
[1.3 0.2]
[1.6 0.6]
[1.9 0.4]
[1.4 0.3]
[1.6 0.2]
[1.4 0.2]
[1.5 0.2]
[1.4 0.2]


> Mínimos de 1.0 e 0.1 para petal length e petal width respectivamente.

> Máximos de 1.9 e 0.6 para petal length e petal width respectivamente.

In [ ]:
Pred_0 = Percep.predict([1.0,0.1])
print(Pred_0)
Pred_1 = Percep.predict([0.0,0.0])
print(Pred_1)

1.0
1.0


> Testando o mínimo dos dados de Setosa, pode-se ver que o peceptron reconhece que pétalas pequenas de mais também são Setosas.



In [ ]:
for i in range(150): #Versicolor
  if i > 49 and i < 100:
    print(X[i])

[4.7 1.4]
[4.5 1.5]
[4.9 1.5]
[4.  1.3]
[4.6 1.5]
[4.5 1.3]
[4.7 1.6]
[3.3 1. ]
[4.6 1.3]
[3.9 1.4]
[3.5 1. ]
[4.2 1.5]
[4. 1.]
[4.7 1.4]
[3.6 1.3]
[4.4 1.4]
[4.5 1.5]
[4.1 1. ]
[4.5 1.5]
[3.9 1.1]
[4.8 1.8]
[4.  1.3]
[4.9 1.5]
[4.7 1.2]
[4.3 1.3]
[4.4 1.4]
[4.8 1.4]
[5.  1.7]
[4.5 1.5]
[3.5 1. ]
[3.8 1.1]
[3.7 1. ]
[3.9 1.2]
[5.1 1.6]
[4.5 1.5]
[4.5 1.6]
[4.7 1.5]
[4.4 1.3]
[4.1 1.3]
[4.  1.3]
[4.4 1.2]
[4.6 1.4]
[4.  1.2]
[3.3 1. ]
[4.2 1.3]
[4.2 1.2]
[4.2 1.3]
[4.3 1.3]
[3.  1.1]
[4.1 1.3]


> Mínimos de 3.0 e 1.0 para petal length e petal width respectivamente.



In [ ]:
Pred_0 = Percep.predict([2.9,1.0])
print(Pred_0)
Pred_1 = Percep.predict([3.0,0.9])
print(Pred_1)
Pred_2 = Percep.predict([3.0,1.0])
print(Pred_2)
Pred_3 = Percep.predict([2.9,1.1])
print(Pred_3)
Pred_4 = Percep.predict([3.1,0.9])
print(Pred_4)
Pred_4 = Percep.predict([3.2,0.9])
print(Pred_4)

1.0
1.0
0.0
0.0
1.0
0.0


> Testando o mínimo dos dados de Versicolor, pode-se ver que o peceptron reconhece que pétalas muito grandes para serem Setosas também o são.